// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/company": {
            "get": {
                "description": "get company",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Company"
                ],
                "summary": "Get Company",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "update company",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company"
                ],
                "summary": "Update company",
                "parameters": [
                    {
                        "description": "Company data",
                        "name": "Company",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpentity.UpdateCompanyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httpentity.UpdateCompanyRequest": {
            "type": "object",
            "required": [
                "address",
                "autocurrency_interval",
                "business_legal_name",
                "business_name",
                "business_type_for_tax_id",
                "city",
                "company_id",
                "company_logo",
                "country",
                "currency_api_id",
                "date_of_establishment",
                "default_currency",
                "email",
                "first_name",
                "industry_id",
                "last_name",
                "mobile",
                "ssn",
                "tax_id",
                "telephone",
                "updated_by",
                "website",
                "zip"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "autocurrency_interval": {
                    "type": "string"
                },
                "business_legal_name": {
                    "type": "string"
                },
                "business_name": {
                    "type": "string"
                },
                "business_type_for_tax_id": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "company_id": {
                    "type": "string"
                },
                "company_logo": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "currency_api_id": {
                    "type": "integer"
                },
                "date_of_establishment": {
                    "type": "string"
                },
                "default_currency": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "industry_id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "last_name": {
                    "type": "string"
                },
                "mobile": {
                    "type": "string"
                },
                "purchase_autocurrency": {
                    "type": "boolean"
                },
                "sales_autocurrency": {
                    "type": "boolean"
                },
                "ssn": {
                    "type": "string"
                },
                "tax_id": {
                    "type": "string"
                },
                "telephone": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                },
                "zip": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:1327",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "ERP core Service API Documentation.",
	Description:      "This is a sample api documentation.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
